/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ee.ria.libdigidocpp;

public class Container {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Container(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Container obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        digidocJNI.delete_Container(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void save(String path) {
    digidocJNI.Container_save__SWIG_0(swigCPtr, this, path);
  }

  public void save() {
    digidocJNI.Container_save__SWIG_1(swigCPtr, this);
  }

  public String mediaType() {
    return digidocJNI.Container_mediaType(swigCPtr, this);
  }

  public void addDataFile(String path, String mediaType) {
    digidocJNI.Container_addDataFile(swigCPtr, this, path, mediaType);
  }

  public DataFiles dataFiles() {
    return new DataFiles(digidocJNI.Container_dataFiles(swigCPtr, this), true);
  }

  public void removeDataFile(long id) {
    digidocJNI.Container_removeDataFile(swigCPtr, this, id);
  }

  public void addAdESSignature(byte[] signature) {
    digidocJNI.Container_addAdESSignature(swigCPtr, this, signature);
  }

  public Signature prepareSignature(Signer signer) {
    long cPtr = digidocJNI.Container_prepareSignature(swigCPtr, this, Signer.getCPtr(signer), signer);
    return (cPtr == 0) ? null : new Signature(cPtr, false);
  }

  public Signatures signatures() {
    return new Signatures(digidocJNI.Container_signatures(swigCPtr, this), true);
  }

  public void removeSignature(long id) {
    digidocJNI.Container_removeSignature(swigCPtr, this, id);
  }

  public Signature sign(Signer signer) {
    long cPtr = digidocJNI.Container_sign(swigCPtr, this, Signer.getCPtr(signer), signer);
    return (cPtr == 0) ? null : new Signature(cPtr, false);
  }

  public static Container create(String path) {
    long cPtr = digidocJNI.Container_create(path);
    return (cPtr == 0) ? null : new Container(cPtr, false);
  }

  public static Container open(String path) {
    long cPtr = digidocJNI.Container_open(path);
    return (cPtr == 0) ? null : new Container(cPtr, false);
  }

}
