/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ee.ria.libdigidocpp;

public class PKCS11Signer extends Signer {
  private long swigCPtr;

  protected PKCS11Signer(long cPtr, boolean cMemoryOwn) {
    super(digidocJNI.PKCS11Signer_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PKCS11Signer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        digidocJNI.delete_PKCS11Signer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PKCS11Signer(String driver) {
    this(digidocJNI.new_PKCS11Signer__SWIG_0(driver), true);
  }

  public PKCS11Signer() {
    this(digidocJNI.new_PKCS11Signer__SWIG_1(), true);
  }

  public void setPin(String pin) {
    digidocJNI.PKCS11Signer_setPin(swigCPtr, this, pin);
  }

}
