/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ee.ria.libdigidocpp;

public class XmlConf extends Conf {
  private long swigCPtr;

  protected XmlConf(long cPtr, boolean cMemoryOwn) {
    super(digidocJNI.XmlConf_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XmlConf obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        digidocJNI.delete_XmlConf(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public XmlConf(String path, String schema) {
    this(digidocJNI.new_XmlConf__SWIG_0(path, schema), true);
  }

  public XmlConf(String path) {
    this(digidocJNI.new_XmlConf__SWIG_1(path), true);
  }

  public XmlConf() {
    this(digidocJNI.new_XmlConf__SWIG_2(), true);
  }

  public int logLevel() {
    return digidocJNI.XmlConf_logLevel(swigCPtr, this);
  }

  public String logFile() {
    return digidocJNI.XmlConf_logFile(swigCPtr, this);
  }

  public String PKCS11Driver() {
    return digidocJNI.XmlConf_PKCS11Driver(swigCPtr, this);
  }

  public String proxyHost() {
    return digidocJNI.XmlConf_proxyHost(swigCPtr, this);
  }

  public String proxyPort() {
    return digidocJNI.XmlConf_proxyPort(swigCPtr, this);
  }

  public String proxyUser() {
    return digidocJNI.XmlConf_proxyUser(swigCPtr, this);
  }

  public String proxyPass() {
    return digidocJNI.XmlConf_proxyPass(swigCPtr, this);
  }

  public boolean proxyForceSSL() {
    return digidocJNI.XmlConf_proxyForceSSL(swigCPtr, this);
  }

  public boolean proxyTunnelSSL() {
    return digidocJNI.XmlConf_proxyTunnelSSL(swigCPtr, this);
  }

  public String digestUri() {
    return digidocJNI.XmlConf_digestUri(swigCPtr, this);
  }

  public String signatureDigestUri() {
    return digidocJNI.XmlConf_signatureDigestUri(swigCPtr, this);
  }

  public String ocsp(String issuer) {
    return digidocJNI.XmlConf_ocsp(swigCPtr, this, issuer);
  }

  public String TSUrl() {
    return digidocJNI.XmlConf_TSUrl(swigCPtr, this);
  }

  public String PKCS12Cert() {
    return digidocJNI.XmlConf_PKCS12Cert(swigCPtr, this);
  }

  public String PKCS12Pass() {
    return digidocJNI.XmlConf_PKCS12Pass(swigCPtr, this);
  }

  public boolean PKCS12Disable() {
    return digidocJNI.XmlConf_PKCS12Disable(swigCPtr, this);
  }

  public boolean TSLAutoUpdate() {
    return digidocJNI.XmlConf_TSLAutoUpdate(swigCPtr, this);
  }

  public String TSLCache() {
    return digidocJNI.XmlConf_TSLCache(swigCPtr, this);
  }

  public boolean TSLOnlineDigest() {
    return digidocJNI.XmlConf_TSLOnlineDigest(swigCPtr, this);
  }

  public int TSLTimeOut() {
    return digidocJNI.XmlConf_TSLTimeOut(swigCPtr, this);
  }

  public void setProxyHost(String host) {
    digidocJNI.XmlConf_setProxyHost(swigCPtr, this, host);
  }

  public void setProxyPort(String port) {
    digidocJNI.XmlConf_setProxyPort(swigCPtr, this, port);
  }

  public void setProxyUser(String user) {
    digidocJNI.XmlConf_setProxyUser(swigCPtr, this, user);
  }

  public void setProxyPass(String pass) {
    digidocJNI.XmlConf_setProxyPass(swigCPtr, this, pass);
  }

  public void setProxyTunnelSSL(boolean enable) {
    digidocJNI.XmlConf_setProxyTunnelSSL(swigCPtr, this, enable);
  }

  public void setPKCS12Cert(String cert) {
    digidocJNI.XmlConf_setPKCS12Cert(swigCPtr, this, cert);
  }

  public void setPKCS12Pass(String pass) {
    digidocJNI.XmlConf_setPKCS12Pass(swigCPtr, this, pass);
  }

  public void setPKCS12Disable(boolean disable) {
    digidocJNI.XmlConf_setPKCS12Disable(swigCPtr, this, disable);
  }

  public void setTSLOnlineDigest(boolean enable) {
    digidocJNI.XmlConf_setTSLOnlineDigest(swigCPtr, this, enable);
  }

  public void setTSLTimeOut(int timeOut) {
    digidocJNI.XmlConf_setTSLTimeOut(swigCPtr, this, timeOut);
  }

}
