language: c++
sudo: required
dist: trusty
os:
- linux
- osx
osx_image: xcode7.3

before_install: if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    ./prepare_osx_build_environment.sh all;
  else
    sudo apt-get update -qq && sudo apt-get install -y libxml-security-c-dev dh-make devscripts dpkg-dev cdbs;
    wget http://www.codesynthesis.com/download/xsd/4.0/linux-gnu/x86_64/xsd_4.0.0-1_amd64.deb && sudo dpkg -i xsd_4.0.0-1_amd64.deb;
  fi
script: export BUILD_NUMBER=${TRAVIS_BUILD_NUMBER} && if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    mkdir build && cd build && cmake -DOPENSSL_ROOT_DIR=/Library/EstonianIDCard ..;
    make zipdebug embedlibs pkgbuild && cd ..;
  else
    VERSION=3.12.2.${TRAVIS_BUILD_NUMBER};
    yes | dh_make --createorig --addmissing --defaultless -p libdigidocpp_${VERSION};
    dch --distribution $(lsb_release -cs) -v ${VERSION} "Release ${VERSION}.";
    dpkg-buildpackage -rfakeroot -us -uc;
  fi

env:
  global:
  - secure: VTpLjRFkVZeqSiP/tea7b5WiMU+PjQJlpny8/QEYazRNhn/uie69aT8VvEdkpsUM1AEx8yPnNmVGShvoNNaOi/AoqynTIKgeGPCj44h6lCnPpByGVur0avc5WrRj2xBbPBBUw1rsL65wZ13MufmRLUwnmmVYQZ3qDBdpgZvCEhA=
addons:
  coverity_scan:
    project:
      name: open-eid/libdigidocpp
      description: Build submitted via Travis CI
    notification_email: raul@metsma.ee
    build_command_prepend: mkdir coverity; cd coverity; cmake ..
    build_command: make
    branch_pattern: coverity_scan

before_deploy:
- export VERSION=${TRAVIS_TAG:1}
- rm -rf build
- cd ..
- mv libdigidocpp libdigidocpp-${VERSION}
- tar czf libdigidocpp-${VERSION}.tar.gz --exclude-vcs libdigidocpp-${VERSION}
deploy:
  provider: releases
  api_key:
    secure: CXl5yp2RQ1VpUWU3j8hsTrQ38TwShaUSIQoAAfHjEdMZvk5GAR0JFzrswpE2AWOEEDHsQV+66DHydqAnv4fYQlAZdXSc44PlNiIC3LV15sVdtoLLZhFBM/UWxDJ1tPMeU654d/SUeXWLd3CMHMrbOEyUA+ymUR1icmc8xHNGqpo=
  file: libdigidocpp-${VERSION}.tar.gz
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
