language: c++
matrix:
  include:
  - os: linux
    env: TARGET=linux
  - os: osx
    env: TARGET=osx
  - os: osx
    env: TARGET=ios
  - os: osx
    env: TARGET=simulator
  - os: osx
    env: TARGET=androidarm
  - os: osx
    env: TARGET=androidarm64
  - os: osx
    env: TARGET=androidx86
sudo: required
dist: trusty
osx_image: xcode7.3
cache: ccache
env:
  global:
  - BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}
  - VERSION=3.12.2.${TRAVIS_BUILD_NUMBER} 
  - secure: VTpLjRFkVZeqSiP/tea7b5WiMU+PjQJlpny8/QEYazRNhn/uie69aT8VvEdkpsUM1AEx8yPnNmVGShvoNNaOi/AoqynTIKgeGPCj44h6lCnPpByGVur0avc5WrRj2xBbPBBUw1rsL65wZ13MufmRLUwnmmVYQZ3qDBdpgZvCEhA=

before_install: case ${TARGET} in
  *ios*|*simulator*|*osx*)
    ./prepare_osx_build_environment.sh all ${TARGET};
    ;;
  *android*)
    brew update;
    brew install swig;
    ./prepare_osx_build_environment.sh all ${TARGET};
    ;;
  *linux*)
    sudo apt-get update -qq && sudo apt-get install -y libxml-security-c-dev dh-make devscripts dpkg-dev cdbs doxygen;
    wget http://www.codesynthesis.com/download/xsd/4.0/linux-gnu/x86_64/xsd_4.0.0-1_amd64.deb && sudo dpkg -i xsd_4.0.0-1_amd64.deb;
    ;;
  esac
script: case ${TARGET} in
  *ios*)
    cd examples/libdigidocpp-ios && ./build-library.sh ${TARGET} && cd ../..;
    ;;
  *simulator*)
    cd examples/libdigidocpp-ios && ./build-library.sh ${TARGET} && cd ../..;
    ;;
  *android*)
    export ANDROID_NDK=$PWD/android-ndk-r10e;
    export PATH=$PATH:/usr/local/Cellar/swig/3.0.8/bin;
    cd examples/libdigidocpp-android && ./build-library.sh ${TARGET} && cd ../..;
    ;;
  *osx*)
    mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/Library/EstonianIDCard -DOPENSSL_ROOT_DIR=/Library/EstonianIDCard ..;
    make zipdebug embedlibs pkgbuild && cd ..;
    ;;
  *linux*)
    yes | dh_make --createorig --addmissing --defaultless -p libdigidocpp_${VERSION};
    dch --distribution $(lsb_release -cs) -v ${VERSION} "Release ${VERSION}.";
    dpkg-buildpackage -rfakeroot -us -uc;
  esac

addons:
  coverity_scan:
    project:
      name: open-eid/libdigidocpp
      description: Build submitted via Travis CI
    notification_email: raul@metsma.ee
    build_command_prepend: mkdir coverity; cd coverity; cmake ..
    build_command: make
    branch_pattern: coverity_scan

before_deploy:
- export VERSION=${TRAVIS_TAG:1}
- rm -rf build
- cd ..
- mv libdigidocpp libdigidocpp-${VERSION}
- tar czf libdigidocpp-${VERSION}.tar.gz --exclude-vcs libdigidocpp-${VERSION}
deploy:
  provider: releases
  api_key:
    secure: CXl5yp2RQ1VpUWU3j8hsTrQ38TwShaUSIQoAAfHjEdMZvk5GAR0JFzrswpE2AWOEEDHsQV+66DHydqAnv4fYQlAZdXSc44PlNiIC3LV15sVdtoLLZhFBM/UWxDJ1tPMeU654d/SUeXWLd3CMHMrbOEyUA+ymUR1icmc8xHNGqpo=
  file: libdigidocpp-${VERSION}.tar.gz
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
