language: c++
matrix:
  include:
  - os: linux
    env: TARGET=ubuntu:16.04
    sudo: false
  - os: linux
    env: TARGET=ubuntu:16.10
    sudo: false
  - os: linux
    env: TARGET=32bit/ubuntu:16.04
    sudo: false
  - os: osx
    env: TARGET=osx
    osx_image: xcode7.3
  - os: osx
    env: TARGET=ios
  - os: osx
    env: TARGET=simulator
  - os: osx
    env: TARGET=androidarm
  - os: osx
    env: TARGET=androidarm64
  - os: osx
    env: TARGET=androidx86
sudo: required
dist: trusty
osx_image: xcode8.2
services:
- docker
cache: ccache
env:
  global:
  - BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}
  - RUN_TESTS=ALL
  - secure: VTpLjRFkVZeqSiP/tea7b5WiMU+PjQJlpny8/QEYazRNhn/uie69aT8VvEdkpsUM1AEx8yPnNmVGShvoNNaOi/AoqynTIKgeGPCj44h6lCnPpByGVur0avc5WrRj2xBbPBBUw1rsL65wZ13MufmRLUwnmmVYQZ3qDBdpgZvCEhA=

before_install: if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    brew install swig;
    ./prepare_osx_build_environment.sh all ${TARGET};
  fi
script: case ${TARGET} in
  *ios*|*simulator*)
    cd examples/libdigidocpp-ios && ./build-library.sh ${TARGET} && cd ../..;
    ;;
  *android*)
    cd examples/libdigidocpp-android && ./build-library.sh ${TARGET} && cd ../..;
    ;;
  *osx*)
    mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/Library/EstonianIDCard -DOPENSSL_ROOT_DIR=/Library/EstonianIDCard ..;
    make all zipdebug embedlibs pkgbuild && cd ..;
    ;;
  *)
    docker run -e BUILD_NUMBER=${TRAVIS_BUILD_NUMBER} -e DEBFULLNAME="Travis" -e DEBEMAIL="travis-ci@travis" -v $(pwd):$(pwd) -t "${TARGET}" /bin/bash -c "cd $(pwd);"'
      apt-get update -qq; 
      apt-get install -y dh-make devscripts dpkg-dev cdbs cmake vim-common xsdcxx libxml-security-c-dev libminizip-dev doxygen libboost-test-dev git;
      export VERSION=$(grep project CMakeLists.txt | egrep -o "([0-9]{1,}\.)+[0-9]{1,}").${BUILD_NUMBER};
      dh_make --createorig --addmissing --defaultless -y -p libdigidocpp_${VERSION};
      dch --distribution $(lsb_release -cs) -v ${VERSION} "Release ${VERSION}.";
      dpkg-buildpackage -rfakeroot -us -uc;
      git clean -dxf';
  esac

addons:
  coverity_scan:
    project:
      name: open-eid/libdigidocpp
    notification_email: raul@metsma.ee
    build_command_prepend: mkdir coverity; cd coverity; cmake ..
    build_command: make
    branch_pattern: coverity_scan

before_deploy:
- export VERSION=${TRAVIS_TAG:1}
- git clean -dfx
- cd ..
- mv libdigidocpp libdigidocpp-${VERSION}
- tar czf libdigidocpp-${VERSION}.tar.gz --exclude-vcs libdigidocpp-${VERSION}
deploy:
  provider: releases
  api_key:
    secure: CXl5yp2RQ1VpUWU3j8hsTrQ38TwShaUSIQoAAfHjEdMZvk5GAR0JFzrswpE2AWOEEDHsQV+66DHydqAnv4fYQlAZdXSc44PlNiIC3LV15sVdtoLLZhFBM/UWxDJ1tPMeU654d/SUeXWLd3CMHMrbOEyUA+ymUR1icmc8xHNGqpo=
  file: libdigidocpp-${VERSION}.tar.gz
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
