libdigidocpp: digidoc::WinSigner Class Reference
digidoc::WinSigner Class Reference
Implements Signer interface for Windows Crypto backends.
#include <WinSigner.h>
Inherits digidoc::Signer.
Public Member Functions
WinSigner (const std::string &pin={}, bool selectFirst=false)
~WinSigner () final
void setPin (const std::string &pin)
void setSelectFirst (bool first)
void setThumbprint (const std::vector< unsigned char > &thumbprint)
Public Member Functions inherited from digidoc::Signer
virtual ~Signer ()
std::string profile () const
std::string userAgent () const
bool usingENProfile () const
std::string city () const
std::string streetAddress () const
std::string stateOrProvince () const
std::string postalCode () const
std::string countryName () const
std::vector< std::string > signerRoles () const
void setMethod (const std::string &method)
void setProfile (const std::string &profile)
void setUserAgent (const std::string &userAgent)
void setENProfile (bool enable)
void setSignatureProductionPlace (const std::string &city, const std::string &stateOrProvince, const std::string &postalCode, const std::string &countryName)
void setSignatureProductionPlaceV2 (const std::string &city, const std::string &streetAddress, const std::string &stateOrProvince, const std::string &postalCode, const std::string &countryName)
void setSignerRoles (const std::vector< std::string > &signerRoles)
Additional Inherited Members
Protected Member Functions inherited from digidoc::Signer
Signer ()
Detailed Description
Implements Signer interface for Windows Crypto backends.
Constructor & Destructor Documentation
WinSigner()
WinSigner::WinSigner (const std::string & pin = {}, bool selectFirst = false)
Initializes WinSigner class
Parameters
pin Optional parameter to skip PIN dialog
selectFirst Optional parameter to skip certificate selection dialog when there is more than one token sertificate available
Exceptions
Exception exception is thrown if the loading failed.
References setPin(), and setSelectFirst().
~WinSigner()
WinSigner::~WinSigner () final
Member Function Documentation
setPin()
void WinSigner::setPin (const std::string & pin)
Sets property PIN
See also
WinSigner::WinSigner
Referenced by WinSigner().
setSelectFirst()
void WinSigner::setSelectFirst (bool first)
Sets property select first certificate
See also
WinSigner::WinSigner
Referenced by WinSigner().
setThumbprint()
void WinSigner::setThumbprint (const std::vector< unsigned char > & thumbprint)
Sets property select certificate with specified thumbprint
See also
WinSigner::WinSigner
The documentation for this class was generated from the following files:
WinSigner.h
WinSigner.cpp