libdigidocpp: digidoc::ConfV4 Class Reference
digidoc::ConfV4 Class Reference
Verison 4 of configuration class to add additonial parameters.
#include <Conf.h>
Inherits digidoc::ConfV3.
Inherited by digidoc::ConfV5, and digidoc::XmlConfV4.
Public Member Functions
ConfV4 ()
~ConfV4 () override
virtual std::vector< X509Cert > verifyServiceCerts () const
Public Member Functions inherited from digidoc::ConfV3
ConfV3 ()
~ConfV3 () override
virtual std::set< std::string > OCSPTMProfiles () const
Public Member Functions inherited from digidoc::ConfV2
ConfV2 ()
~ConfV2 () override
virtual X509Cert verifyServiceCert () const
Public Member Functions inherited from digidoc::Conf
Conf ()
virtual ~Conf ()
virtual int logLevel () const
virtual std::string logFile () const
virtual DIGIDOCPP_DEPRECATED std::string libdigidocConf () const
virtual DIGIDOCPP_DEPRECATED std::string certsPath () const
virtual std::string xsdPath () const
virtual std::string PKCS11Driver () const
virtual std::string proxyHost () const
virtual std::string proxyPort () const
virtual std::string proxyUser () const
virtual std::string proxyPass () const
virtual bool proxyForceSSL () const
virtual bool proxyTunnelSSL () const
virtual std::string digestUri () const
virtual std::string signatureDigestUri () const
virtual std::string ocsp (const std::string &issuer) const
virtual std::string TSUrl () const
virtual std::string verifyServiceUri () const
virtual DIGIDOCPP_DEPRECATED std::string PKCS12Cert () const
virtual DIGIDOCPP_DEPRECATED std::string PKCS12Pass () const
virtual DIGIDOCPP_DEPRECATED bool PKCS12Disable () const
virtual bool TSLAllowExpired () const
virtual bool TSLAutoUpdate () const
virtual std::string TSLCache () const
virtual std::vector< X509Cert > TSLCerts () const
virtual bool TSLOnlineDigest () const
virtual int TSLTimeOut () const
virtual std::string TSLUrl () const
Static Public Member Functions
static ConfV4 * instance ()
Static Public Member Functions inherited from digidoc::ConfV3
static ConfV3 * instance ()
Static Public Member Functions inherited from digidoc::ConfV2
static ConfV2 * instance ()
Static Public Member Functions inherited from digidoc::Conf
static void init (Conf *conf)
static Conf * instance ()
Detailed Description
Verison 4 of configuration class to add additonial parameters.
Conf contains virtual members and is not leaf class we need create subclasses to keep binary compatibility https://techbase.kde.org/Policies/Binary_Compatibility_Issues_With_C++#Adding_new_virtual_functions_to_leaf_classes
See also
digidoc::ConfV3
Deprecated:
Use digidoc::ConfV5
See also
Configuration parameters
Constructor & Destructor Documentation
ConfV4()
ConfV4::ConfV4 () default
Version 4 config with new parameters
~ConfV4()
ConfV4::~ConfV4 () override default
Member Function Documentation
instance()
ConfV4 * ConfV4::instance () static
Return global config instance object
References digidoc::Conf::instance().
verifyServiceCerts()
vector< X509Cert > ConfV4::verifyServiceCerts () const virtual
Gets verify service Certs
Reimplemented in digidoc::XmlConfV4, and digidoc::XmlConfV5.
References digidoc::ConfV2::verifyServiceCert().
Referenced by digidoc::XmlConfV4::verifyServiceCerts(), and digidoc::XmlConfV5::verifyServiceCerts().
The documentation for this class was generated from the following files:
Conf.h
Conf.cpp