libdigidocpp: digidoc::Conf Class Reference
digidoc::Conf Class Reference
Configuration class which can reimplemented and virtual methods overloaded.
#include <Conf.h>
Inherited by digidoc::ConfV2, and digidoc::XmlConf.
Public Member Functions
Conf ()
virtual ~Conf ()
virtual int logLevel () const
virtual std::string logFile () const
virtual DIGIDOCPP_DEPRECATED std::string libdigidocConf () const
virtual DIGIDOCPP_DEPRECATED std::string certsPath () const
virtual std::string xsdPath () const
virtual std::string PKCS11Driver () const
virtual std::string proxyHost () const
virtual std::string proxyPort () const
virtual std::string proxyUser () const
virtual std::string proxyPass () const
virtual bool proxyForceSSL () const
virtual bool proxyTunnelSSL () const
virtual std::string digestUri () const
virtual std::string signatureDigestUri () const
virtual std::string ocsp (const std::string &issuer) const
virtual std::string TSUrl () const
virtual std::string verifyServiceUri () const
virtual DIGIDOCPP_DEPRECATED std::string PKCS12Cert () const
virtual DIGIDOCPP_DEPRECATED std::string PKCS12Pass () const
virtual DIGIDOCPP_DEPRECATED bool PKCS12Disable () const
virtual bool TSLAllowExpired () const
virtual bool TSLAutoUpdate () const
virtual std::string TSLCache () const
virtual std::vector< X509Cert > TSLCerts () const
virtual bool TSLOnlineDigest () const
virtual int TSLTimeOut () const
virtual std::string TSLUrl () const
Static Public Member Functions
static void init (Conf *conf)
static Conf * instance ()
Detailed Description
Configuration class which can reimplemented and virtual methods overloaded.
Deprecated:
Use digidoc::ConfV5
See also
Configuration parameters
Constructor & Destructor Documentation
Conf()
Conf::Conf () default
Configuration parameters
~Conf()
Conf::~Conf () virtual default
Member Function Documentation
certsPath()
string Conf::certsPath () const virtual
Gets Certificate store location.
Deprecated:
Unused
digestUri()
string Conf::digestUri () const virtual
Return default digest type as URI
Reimplemented in digidoc::XmlConf, digidoc::XmlConfV2, digidoc::XmlConfV3, digidoc::XmlConfV4, and digidoc::XmlConfV5.
Referenced by signatureDigestUri().
init()
void Conf::init (Conf * conf) static
Init global Conf with conf
Referenced by digidoc::initialize(), and digidoc::terminate().
instance()
Conf * Conf::instance () static
Return global config instance object
Referenced by digidoc::initialize(), digidoc::ConfV2::instance(), digidoc::ConfV3::instance(), digidoc::ConfV4::instance(), digidoc::ConfV5::instance(), digidoc::XmlConf::instance(), digidoc::XmlConfV2::instance(), digidoc::XmlConfV3::instance(), digidoc::XmlConfV4::instance(), digidoc::XmlConfV5::instance(), and digidoc::PKCS11Signer::PKCS11Signer().
libdigidocConf()
string Conf::libdigidocConf () const virtual
Returns libdigidoc library configuration file's (digidoc.ini) file location
Deprecated:
Unused
logFile()
string Conf::logFile () const virtual
Gets log file location. Default log goes to standard out stream
Reimplemented in digidoc::XmlConf, digidoc::XmlConfV2, digidoc::XmlConfV3, digidoc::XmlConfV4, and digidoc::XmlConfV5.
logLevel()
int Conf::logLevel () const virtual
Returns log level. 0 = Error 1 = Warn 2 = Info 3 = Debug
Reimplemented in digidoc::XmlConf, digidoc::XmlConfV2, digidoc::XmlConfV3, digidoc::XmlConfV4, and digidoc::XmlConfV5.
ocsp()
string Conf::ocsp (const std::string & issuer) const virtual
Return OCSP request URL
Parameters
issuer OCSP issuer.
Reimplemented in digidoc::XmlConf, digidoc::XmlConfV2, digidoc::XmlConfV3, digidoc::XmlConfV4, and digidoc::XmlConfV5.
Referenced by digidoc::XmlConf::ocsp(), digidoc::XmlConfV2::ocsp(), digidoc::XmlConfV3::ocsp(), digidoc::XmlConfV4::ocsp(), and digidoc::XmlConfV5::ocsp().
PKCS11Driver()
string Conf::PKCS11Driver () const virtual
Returns PKCS11 driver file path
Reimplemented in digidoc::XmlConf, digidoc::XmlConfV2, digidoc::XmlConfV3, digidoc::XmlConfV4, and digidoc::XmlConfV5.
Referenced by digidoc::PKCS11Signer::PKCS11Signer().
PKCS12Cert()
string Conf::PKCS12Cert () const virtual
Gets PKCS12 certificate file location.
Used for signing OCSP request
Reimplemented in digidoc::XmlConf, digidoc::XmlConfV2, digidoc::XmlConfV3, digidoc::XmlConfV4, and digidoc::XmlConfV5.
PKCS12Disable()
bool Conf::PKCS12Disable () const virtual
Gets PKCS12 usage.
See also
digidoc::Conf::PKCS12Cert
Reimplemented in digidoc::XmlConf, digidoc::XmlConfV2, digidoc::XmlConfV3, digidoc::XmlConfV4, and digidoc::XmlConfV5.
PKCS12Pass()
string Conf::PKCS12Pass () const virtual
Gets PKCS12 password.
See also
digidoc::Conf::PKCS12Cert
Reimplemented in digidoc::XmlConf, digidoc::XmlConfV2, digidoc::XmlConfV3, digidoc::XmlConfV4, and digidoc::XmlConfV5.
proxyForceSSL()
bool Conf::proxyForceSSL () const virtual
Redirect SSL traffic over proxy server Default: false
Reimplemented in digidoc::XmlConf, digidoc::XmlConfV2, digidoc::XmlConfV3, digidoc::XmlConfV4, and digidoc::XmlConfV5.
proxyHost()
string Conf::proxyHost () const virtual
Gets proxy host address.
Reimplemented in digidoc::XmlConf, digidoc::XmlConfV2, digidoc::XmlConfV3, digidoc::XmlConfV4, and digidoc::XmlConfV5.
proxyPass()
string Conf::proxyPass () const virtual
Gets proxy login password.
Reimplemented in digidoc::XmlConf, digidoc::XmlConfV2, digidoc::XmlConfV3, digidoc::XmlConfV4, and digidoc::XmlConfV5.
proxyPort()
string Conf::proxyPort () const virtual
Gets proxy port number.
Reimplemented in digidoc::XmlConf, digidoc::XmlConfV2, digidoc::XmlConfV3, digidoc::XmlConfV4, and digidoc::XmlConfV5.
proxyTunnelSSL()
bool Conf::proxyTunnelSSL () const virtual
Tunnel SSL traffic over proxy server Default: false
Reimplemented in digidoc::XmlConf, digidoc::XmlConfV2, digidoc::XmlConfV3, digidoc::XmlConfV4, and digidoc::XmlConfV5.
proxyUser()
string Conf::proxyUser () const virtual
Gets proxy user name.
Reimplemented in digidoc::XmlConf, digidoc::XmlConfV2, digidoc::XmlConfV3, digidoc::XmlConfV4, and digidoc::XmlConfV5.
signatureDigestUri()
string Conf::signatureDigestUri () const virtual
Gets signature digest URI
Reimplemented in digidoc::XmlConf, digidoc::XmlConfV2, digidoc::XmlConfV3, digidoc::XmlConfV4, and digidoc::XmlConfV5.
References digestUri().
TSLAllowExpired()
bool Conf::TSLAllowExpired () const virtual
Allow expired TSL lists
TSLAutoUpdate()
bool Conf::TSLAutoUpdate () const virtual
Download new TSL list when it is expired or invalid
Reimplemented in digidoc::XmlConf, digidoc::XmlConfV2, digidoc::XmlConfV3, digidoc::XmlConfV4, and digidoc::XmlConfV5.
TSLCache()
string Conf::TSLCache () const virtual
TSL cache path in local file system
Reimplemented in digidoc::XmlConf, digidoc::XmlConfV2, digidoc::XmlConfV3, digidoc::XmlConfV4, and digidoc::XmlConfV5.
TSLCerts()
vector< X509Cert > Conf::TSLCerts () const virtual
TSL master list's (LOTL) signing certificates
TSLOnlineDigest()
bool Conf::TSLOnlineDigest () const virtual
Compare local TSL digest with digest published online to check for newer version
Reimplemented in digidoc::XmlConf, digidoc::XmlConfV2, digidoc::XmlConfV3, digidoc::XmlConfV4, and digidoc::XmlConfV5.
TSLTimeOut()
int Conf::TSLTimeOut () const virtual
Gets TSL downloading connection's current timeout value
Reimplemented in digidoc::XmlConf, digidoc::XmlConfV2, digidoc::XmlConfV3, digidoc::XmlConfV4, and digidoc::XmlConfV5.
TSLUrl()
string Conf::TSLUrl () const virtual
TSL master list's (LOTL) URL
TSUrl()
string Conf::TSUrl () const virtual
Returns default time-stamp server URL
Reimplemented in digidoc::XmlConf, digidoc::XmlConfV2, digidoc::XmlConfV3, digidoc::XmlConfV4, and digidoc::XmlConfV5.
verifyServiceUri()
string Conf::verifyServiceUri () const virtual
Gets verify service URI
Reimplemented in digidoc::XmlConf, digidoc::XmlConfV2, digidoc::XmlConfV3, digidoc::XmlConfV4, and digidoc::XmlConfV5.
xsdPath()
string Conf::xsdPath () const virtual
Gets XSD schema files path
The documentation for this class was generated from the following files:
Conf.h
Conf.cpp