libdigidocpp: digidoc Namespace Reference
digidoc Namespace Reference
Classes
class Conf
Configuration class which can reimplemented and virtual methods overloaded.
class ConfV2
Verison 2 of configuration class to add additonial parameters.
class ConfV3
Verison 3 of configuration class to add additonial parameters.
class ConfV4
Verison 4 of configuration class to add additonial parameters.
class ConfV5
Verison 5 of configuration class to add additonial parameters.
class Container
Offers functionality for handling data files and signatures in a container.
struct ContainerOpenCB
Used on container open to provide additional info.
class DataFile
Data file wrapper providing methods for handling signed files or files to be signed in Container.
class DataFilePrivate
class Exception
Base exception class of the digidoc implementation.
class PKCS11Signer
Implements Signer interface for ID-Cards, which support PKCS#11 protocol.
class PKCS12Signer
Implements Signer interface for PKCS#12 files.
class Signature
Signature interface. Provides interface for handling a signature and the corresponding OCSP response properties.
class Signer
Signer interface. Provides interface for signing documents.
struct TSAInfo
class WinSigner
Implements Signer interface for Windows Crypto backends.
class X509Cert
Wrapper for OpenSSL X509 certificate structure.
class XmlConf
XML Configuration class.
class XmlConfV2
Version 2 of XML Configuration class.
class XmlConfV3
Version 3 of XML Configuration class.
class XmlConfV4
Version 4 of XML Configuration class.
class XmlConfV5
Version 5 of XML Configuration class.
Typedefs
using ConfCurrent = ConfV5
using initCallBack = void(*)(const Exception *e)
using XmlConfCurrent = XmlConfV5
Functions
int initXmlSecCallback ()
DIGIDOCPP_EXPORT std::string appInfo ()
DIGIDOCPP_EXPORT void initialize (const std::string &appInfo="libdigidocpp", initCallBack callBack=nullptr)
DIGIDOCPP_EXPORT void initialize (const std::string &appInfo, const std::string &userAgent, initCallBack callBack=nullptr)
DIGIDOCPP_EXPORT void terminate ()
DIGIDOCPP_EXPORT std::string userAgent ()
DIGIDOCPP_EXPORT std::string version ()
Variables
constexpr unsigned long MAX_MEM_FILE = 500UL*1024UL*1024UL
Typedef Documentation
ConfCurrent
digidoc::ConfCurrent
Reference to latest ConfV5 class.
initCallBack
initCallBack
Parameters
e digidoc::Exception that occured on initialization
Used in digidoc::initialize to notfiy if the initalization has completed
XmlConfCurrent
digidoc::XmlConfCurrent
Reference to latest XmlConfV5 class
Function Documentation
appInfo()
string digidoc::appInfo ()
Returns registered application name
Referenced by initialize(), and initialize().
initialize() [1/2]
void digidoc::initialize (const std::string & appInfo, const std::string & userAgent, initCallBack callBack = nullptr)
Libdigidocpp’s initialization method: initializes dependent libraries, loads configuration settings from default configuration files (see Configuring Libdigidocpp) and initializes certificate store using TSL lists
Parameters
appInfo Application name for container comments
userAgent Application info for user agent string
callBack Callback when background thread TSL loading is completed
References appInfo(), digidoc::Conf::init(), initXmlSecCallback(), digidoc::Conf::instance(), and userAgent().
initialize() [2/2]
void digidoc::initialize (const std::string & appInfo = "libdigidocpp", initCallBack callBack = nullptr)
Libdigidocpp’s initialization method: initializes dependent libraries, loads configuration settings from default configuration files (see Configuring Libdigidocpp) and initializes certificate store using TSL lists
Parameters
appInfo Application name for user agent string and container comments
callBack Callback when background thread TSL loading is completed
References appInfo(), and initialize().
Referenced by initialize().
initXmlSecCallback()
int digidoc::initXmlSecCallback ()
Referenced by initialize().
terminate()
void digidoc::terminate ()
The termination method closes libraries used in Libdigidocpp implementation and deletes temporary files that may have been written to disk when working with the library.
References digidoc::Conf::init().
userAgent()
string digidoc::userAgent ()
Returns user-agent info
Referenced by initialize(), and digidoc::Signer::sign().
version()
string digidoc::version ()
Returns libdigidocpp library version
Variable Documentation
MAX_MEM_FILE
constexpr unsigned long digidoc::MAX_MEM_FILE = 500UL*1024UL*1024UL constexpr