libdigidocpp: digidoc::XMLNode Struct Reference
digidoc::XMLNode Struct Reference
#include <XMLDocument.h>
Classes
struct iterator
Public Member Functions
constexpr iterator begin () const noexcept
constexpr iterator end () const noexcept
XMLNode addChild (sv name, sv ns={}) const noexcept
xmlNsPtr addNS (sv href, sv prefix={}) const noexcept
xmlNsPtr searchNS (sv ns) const noexcept
constexpr sv property (sv name, sv ns={}) const noexcept
void setProperty (sv name, sv value, sv ns) const noexcept
void setProperty (sv name, sv value, xmlNsPtr ns={}) const noexcept
XMLNode & operator= (sv text) noexcept
constexpr XMLNode operator/ (sv name) const noexcept
Public Member Functions inherited from digidoc::XMLElem< xmlNode >
constexpr sv name () const noexcept
constexpr sv ns () const noexcept
constexpr operator bool () const noexcept
constexpr auto & operator++ () noexcept
constexpr auto operator++ (int) noexcept
constexpr operator sv () const noexcept
Static Public Member Functions
static iterator erase (iterator pos) noexcept
Static Public Member Functions inherited from digidoc::XMLElem< xmlNode >
constexpr static C find (C n, xmlElementType type) noexcept
constexpr static C find (C n, sv name, sv ns) noexcept
constexpr static sv to_string_view (const xmlChar *str) noexcept
Additional Inherited Members
Public Types inherited from digidoc::XMLElem< xmlNode >
using value_type = xmlNode
using pointer = value_type *
using sv = std::string_view
using pcxmlChar = const xmlChar *
Public Attributes inherited from digidoc::XMLElem< xmlNode >
pointer d
Member Function Documentation
addChild()
XMLNode digidoc::XMLNode::addChild (sv name, sv ns = {}) const inline noexcept
addNS()
xmlNsPtr digidoc::XMLNode::addNS (sv href, sv prefix = {}) const inline noexcept
begin()
constexpr iterator digidoc::XMLNode::begin () const inline constexpr noexcept
References digidoc::XMLElem< xmlNode >::d, and digidoc::XMLElem< xmlNode >::find().
Referenced by operator/().
end()
constexpr iterator digidoc::XMLNode::end () const inline constexpr noexcept
erase()
static iterator digidoc::XMLNode::erase (iterator pos) inline static noexcept
operator/()
constexpr XMLNode digidoc::XMLNode::operator/ (sv name) const inline constexpr noexcept
References begin(), digidoc::XMLElem< xmlNode >::find(), digidoc::XMLElem< xmlNode >::name(), and digidoc::XMLElem< xmlNode >::ns().
operator=()
XMLNode& digidoc::XMLNode::operator= (sv text) inline noexcept
References digidoc::XMLElem< xmlNode >::d.
property()
constexpr sv digidoc::XMLNode::property (sv name, sv ns = {}) const inline constexpr noexcept
searchNS()
xmlNsPtr digidoc::XMLNode::searchNS (sv ns) const inline noexcept
References digidoc::XMLElem< xmlNode >::d, and digidoc::XMLElem< xmlNode >::ns().
Referenced by setProperty().
setProperty() [1/2]
void digidoc::XMLNode::setProperty (sv name, sv value, sv ns) const inline noexcept
References digidoc::XMLElem< xmlNode >::name(), digidoc::XMLElem< xmlNode >::ns(), and searchNS().
setProperty() [2/2]
void digidoc::XMLNode::setProperty (sv name, sv value, xmlNsPtr ns = {}) const inline noexcept
The documentation for this struct was generated from the following file:
XMLDocument.h