libdigidocpp: digidoc::XMLElem< T > Struct Template Reference
digidoc::XMLElem< T > Struct Template Reference
#include <XMLDocument.h>
Public Types
using value_type = T
using pointer = value_type *
using sv = std::string_view
using pcxmlChar = const xmlChar *
Public Member Functions
constexpr sv name () const noexcept
constexpr sv ns () const noexcept
constexpr operator bool () const noexcept
constexpr auto & operator++ () noexcept
constexpr auto operator++ (int) noexcept
constexpr operator sv () const noexcept
Static Public Member Functions
template<class C >
constexpr static C find (C n, xmlElementType type) noexcept
template<class C >
constexpr static C find (C n, sv name, sv ns) noexcept
constexpr static sv to_string_view (const xmlChar *str) noexcept
Public Attributes
pointer d {}
Member Typedef Documentation
pcxmlChar
template<class T > using digidoc::XMLElem< T >::pcxmlChar = const xmlChar *
pointer
template<class T > using digidoc::XMLElem< T >::pointer = value_type*
sv
template<class T > using digidoc::XMLElem< T >::sv = std::string_view
value_type
template<class T > using digidoc::XMLElem< T >::value_type = T
Member Function Documentation
find() [1/2]
template<class T > template<class C > constexpr static C digidoc::XMLElem< T >::find (C n, sv name, sv ns) inline static constexpr noexcept
References digidoc::XMLElem< T >::name(), and digidoc::XMLElem< T >::ns().
find() [2/2]
template<class T > template<class C > constexpr static C digidoc::XMLElem< T >::find (C n, xmlElementType type) inline static constexpr noexcept
Referenced by digidoc::XMLElem< T >::operator sv(), and digidoc::XMLElem< T >::operator++().
name()
template<class T > constexpr sv digidoc::XMLElem< T >::name () const inline constexpr noexcept
References digidoc::XMLElem< T >::d, and digidoc::XMLElem< T >::to_string_view().
Referenced by digidoc::XMLElem< T >::find().
ns()
template<class T > constexpr sv digidoc::XMLElem< T >::ns () const inline constexpr noexcept
References digidoc::XMLElem< T >::d, and digidoc::XMLElem< T >::to_string_view().
Referenced by digidoc::XMLElem< T >::find().
operator bool()
template<class T > constexpr digidoc::XMLElem< T >::operator bool () const inline constexpr noexcept
References digidoc::XMLElem< T >::d.
operator sv()
template<class T > constexpr digidoc::XMLElem< T >::operator sv () const inline constexpr noexcept
References digidoc::XMLElem< T >::d, digidoc::XMLElem< T >::find(), and digidoc::XMLElem< T >::to_string_view().
operator++() [1/2]
template<class T > constexpr auto& digidoc::XMLElem< T >::operator++ () inline constexpr noexcept
References digidoc::XMLElem< T >::d, and digidoc::XMLElem< T >::find().
operator++() [2/2]
template<class T > constexpr auto digidoc::XMLElem< T >::operator++ (int) inline constexpr noexcept
References digidoc::XMLElem< T >::d, and digidoc::XMLElem< T >::find().
to_string_view()
template<class T > constexpr static sv digidoc::XMLElem< T >::to_string_view (const xmlChar * str) inline static constexpr noexcept
Referenced by digidoc::XMLElem< T >::name(), digidoc::XMLElem< T >::ns(), and digidoc::XMLElem< T >::operator sv().
Member Data Documentation
d
template<class T > pointer digidoc::XMLElem< T >::d {}
Referenced by digidoc::XMLElem< T >::name(), digidoc::XMLElem< T >::ns(), digidoc::XMLElem< T >::operator bool(), digidoc::XMLElem< T >::operator sv(), and digidoc::XMLElem< T >::operator++().
The documentation for this struct was generated from the following file:
XMLDocument.h