libdigidocpp: digidoc::XMLDocument Struct Reference
digidoc::XMLDocument Struct Reference
#include <XMLDocument.h>
Public Member Functions
XMLDocument (element_type *ptr={}, const XMLName &n={}) noexcept
XMLDocument (std::string_view path, const XMLName &n={}) noexcept
void c14n (Digest *digest, std::string_view algo, XMLNode node)
bool save (std::string_view path) const noexcept
bool save (std::ostream &os) const noexcept
void validateSchema (const std::string &schemaPath) const
Public Member Functions inherited from digidoc::XMLNode
constexpr iterator begin () const noexcept
constexpr iterator end () const noexcept
xmlNsPtr addNS (sv href, sv prefix={}) const noexcept
xmlNsPtr searchNS (sv ns) const noexcept
constexpr sv property (sv name, sv ns={}) const noexcept
void setProperty (sv name, sv value, sv ns) const noexcept
void setProperty (sv name, sv value, xmlNsPtr ns={}) const noexcept
operator std::vector< unsigned char > ()
XMLNode & operator= (sv text) noexcept
constexpr XMLNode operator/ (sv name) const noexcept
constexpr XMLNode operator/ (const XMLName &name) const noexcept
XMLNode operator+ (const XMLName &name) const noexcept
XMLNode operator+ (const char *name) const noexcept
constexpr auto operator+ (int n) noexcept
XMLNode & operator= (const std::vector< unsigned char > &data)
Public Member Functions inherited from digidoc::XMLElem< xmlNode >
constexpr auto children (P p, xmlElementType type=XML_ELEMENT_NODE) const noexcept
constexpr sv name () const noexcept
constexpr sv ns () const noexcept
constexpr operator bool () const noexcept
constexpr auto & operator++ () noexcept
constexpr auto operator++ (int) noexcept
constexpr operator sv () const noexcept
Static Public Member Functions
static XMLDocument openStream (std::istream &is, const XMLName &name={}, bool hugeFile=false)
static XMLDocument create (std::string_view name={}, std::string_view href={}, std::string_view prefix={}) noexcept
static bool verifySignature (XMLNode signature, [[maybe_unused]] Exception *e={}) noexcept
static void schemaValidationError (void *ctx, const char *msg,...) noexcept
static void schemaValidationWarning (void *, const char *msg,...) noexcept
Static Public Member Functions inherited from digidoc::XMLNode
static iterator erase (iterator pos) noexcept
Static Public Member Functions inherited from digidoc::XMLElem< xmlNode >
constexpr static auto safe (C c, P p) noexcept
constexpr static C find (C n, xmlElementType type) noexcept
constexpr static C find (C n, sv name, sv ns) noexcept
constexpr static sv to_string_view (C d, P p) noexcept
Static Public Attributes
static constexpr std::string_view C14D_ID_1_0 {"http://www.w3.org/TR/2001/REC-xml-c14n-20010315"}
static constexpr std::string_view C14D_ID_1_0_COM {"http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments"}
static constexpr std::string_view C14D_ID_1_1 {"http://www.w3.org/2006/12/xml-c14n11"}
static constexpr std::string_view C14D_ID_1_1_COM {"http://www.w3.org/2006/12/xml-c14n11#WithComments"}
static constexpr std::string_view C14D_ID_1_0_EXC {"http://www.w3.org/2001/10/xml-exc-c14n#"}
static constexpr std::string_view C14D_ID_1_0_EXC_COM {"http://www.w3.org/2001/10/xml-exc-c14n#WithComments"}
Static Public Attributes inherited from digidoc::XMLElem< xmlNode >
static constexpr sv whitespace
Additional Inherited Members
Public Types inherited from digidoc::XMLElem< xmlNode >
using value_type = xmlNode
using pointer = value_type *
using sv = std::string_view
using pcxmlChar = const xmlChar *
Public Attributes inherited from digidoc::XMLElem< xmlNode >
pointer d
Constructor & Destructor Documentation
XMLDocument() [1/2]
digidoc::XMLDocument::XMLDocument (element_type * ptr = {}, const XMLName & n = {}) inline noexcept
XMLDocument() [2/2]
digidoc::XMLDocument::XMLDocument (std::string_view path, const XMLName & n = {}) inline noexcept
Member Function Documentation
c14n()
void digidoc::XMLDocument::c14n (Digest * digest, std::string_view algo, XMLNode node) inline
References C14D_ID_1_0, C14D_ID_1_0_COM, C14D_ID_1_0_EXC, C14D_ID_1_0_EXC_COM, C14D_ID_1_1, C14D_ID_1_1_COM, digidoc::XMLElem< T >::d, and digidoc::make_unique_ptr().
create()
static XMLDocument digidoc::XMLDocument::create (std::string_view name = {}, std::string_view href = {}, std::string_view prefix = {}) inline static noexcept
openStream()
static XMLDocument digidoc::XMLDocument::openStream (std::istream & is, const XMLName & name = {}, bool hugeFile = false) inline static
save() [1/2]
bool digidoc::XMLDocument::save (std::ostream & os) const inline noexcept
save() [2/2]
bool digidoc::XMLDocument::save (std::string_view path) const inline noexcept
schemaValidationError()
static void digidoc::XMLDocument::schemaValidationError (void * ctx, const char * msg, ...) inline static noexcept
References digidoc::Exception::addCause().
Referenced by validateSchema().
schemaValidationWarning()
static void digidoc::XMLDocument::schemaValidationWarning (void * , const char * msg, ...) inline static noexcept
Referenced by validateSchema().
validateSchema()
void digidoc::XMLDocument::validateSchema (const std::string & schemaPath) const inline
References digidoc::make_unique_ptr(), schemaValidationError(), and schemaValidationWarning().
verifySignature()
static bool digidoc::XMLDocument::verifySignature (XMLNode signature, [[maybe_unused] ] Exception * e = {}) inline static noexcept
Member Data Documentation
C14D_ID_1_0
constexpr std::string_view digidoc::XMLDocument::C14D_ID_1_0 {"http://www.w3.org/TR/2001/REC-xml-c14n-20010315"} static constexpr
Referenced by c14n().
C14D_ID_1_0_COM
constexpr std::string_view digidoc::XMLDocument::C14D_ID_1_0_COM {"http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments"} static constexpr
Referenced by c14n().
C14D_ID_1_0_EXC
constexpr std::string_view digidoc::XMLDocument::C14D_ID_1_0_EXC {"http://www.w3.org/2001/10/xml-exc-c14n#"} static constexpr
Referenced by c14n().
C14D_ID_1_0_EXC_COM
constexpr std::string_view digidoc::XMLDocument::C14D_ID_1_0_EXC_COM {"http://www.w3.org/2001/10/xml-exc-c14n#WithComments"} static constexpr
Referenced by c14n().
C14D_ID_1_1
constexpr std::string_view digidoc::XMLDocument::C14D_ID_1_1 {"http://www.w3.org/2006/12/xml-c14n11"} static constexpr
Referenced by c14n().
C14D_ID_1_1_COM
constexpr std::string_view digidoc::XMLDocument::C14D_ID_1_1_COM {"http://www.w3.org/2006/12/xml-c14n11#WithComments"} static constexpr
Referenced by c14n().
The documentation for this struct was generated from the following file:
XMLDocument.h