/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ee.ria.libdigidocpp;

public class ConfV3 extends ConfV2 {
  private transient long swigCPtr;

  protected ConfV3(long cPtr, boolean cMemoryOwn) {
    super(digidocJNI.ConfV3_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConfV3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        digidocJNI.delete_ConfV3(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ConfV3() {
    this(digidocJNI.new_ConfV3(), true);
  }

  public static ConfV3 instance() {
    long cPtr = digidocJNI.ConfV3_instance();
    return (cPtr == 0) ? null : new ConfV3(cPtr, false);
  }

}
