/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ee.ria.libdigidocpp;

public class DataFiles extends java.util.AbstractList<DataFile> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DataFiles(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataFiles obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        digidocJNI.delete_DataFiles(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DataFiles(DataFile[] initialElements) {
    this();
    reserve(initialElements.length);

    for (DataFile element : initialElements) {
      add(element);
    }
  }

  public DataFiles(Iterable<DataFile> initialElements) {
    this();
    for (DataFile element : initialElements) {
      add(element);
    }
  }

  public DataFile get(int index) {
    return doGet(index);
  }

  public DataFile set(int index, DataFile e) {
    return doSet(index, e);
  }

  public boolean add(DataFile e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, DataFile e) {
    modCount++;
    doAdd(index, e);
  }

  public DataFile remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public DataFiles() {
    this(digidocJNI.new_DataFiles__SWIG_0(), true);
  }

  public DataFiles(DataFiles other) {
    this(digidocJNI.new_DataFiles__SWIG_1(DataFiles.getCPtr(other), other), true);
  }

  public long capacity() {
    return digidocJNI.DataFiles_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    digidocJNI.DataFiles_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return digidocJNI.DataFiles_isEmpty(swigCPtr, this);
  }

  public void clear() {
    digidocJNI.DataFiles_clear(swigCPtr, this);
  }

  public DataFiles(int count, DataFile value) {
    this(digidocJNI.new_DataFiles__SWIG_2(count, DataFile.getCPtr(value), value), true);
  }

  private int doSize() {
    return digidocJNI.DataFiles_doSize(swigCPtr, this);
  }

  private void doAdd(DataFile x) {
    digidocJNI.DataFiles_doAdd__SWIG_0(swigCPtr, this, DataFile.getCPtr(x), x);
  }

  private void doAdd(int index, DataFile x) {
    digidocJNI.DataFiles_doAdd__SWIG_1(swigCPtr, this, index, DataFile.getCPtr(x), x);
  }

  private DataFile doRemove(int index) {
    long cPtr = digidocJNI.DataFiles_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new DataFile(cPtr, false);
  }

  private DataFile doGet(int index) {
    long cPtr = digidocJNI.DataFiles_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new DataFile(cPtr, false);
  }

  private DataFile doSet(int index, DataFile val) {
    long cPtr = digidocJNI.DataFiles_doSet(swigCPtr, this, index, DataFile.getCPtr(val), val);
    return (cPtr == 0) ? null : new DataFile(cPtr, false);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    digidocJNI.DataFiles_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
