/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ee.ria.libdigidocpp;

public class DigiDocConf extends XmlConfV3 {
  private transient long swigCPtr;

  protected DigiDocConf(long cPtr, boolean cMemoryOwn) {
    super(digidocJNI.DigiDocConf_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DigiDocConf obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        digidocJNI.delete_DigiDocConf(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DigiDocConf(String _cache) {
    this(digidocJNI.new_DigiDocConf(_cache), true);
  }

  public static DigiDocConf instance() {
    long cPtr = digidocJNI.DigiDocConf_instance();
    return (cPtr == 0) ? null : new DigiDocConf(cPtr, false);
  }

  public int logLevel() {
    return digidocJNI.DigiDocConf_logLevel(swigCPtr, this);
  }

  public String logFile() {
    return digidocJNI.DigiDocConf_logFile(swigCPtr, this);
  }

  public String ocsp(String issuer) {
    return digidocJNI.DigiDocConf_ocsp(swigCPtr, this, issuer);
  }

  public String PKCS12Cert() {
    return digidocJNI.DigiDocConf_PKCS12Cert(swigCPtr, this);
  }

  public String TSLCache() {
    return digidocJNI.DigiDocConf_TSLCache(swigCPtr, this);
  }

  public String TSLUrl() {
    return digidocJNI.DigiDocConf_TSLUrl(swigCPtr, this);
  }

  public String verifyServiceUri() {
    return digidocJNI.DigiDocConf_verifyServiceUri(swigCPtr, this);
  }

  public String xsdPath() {
    return digidocJNI.DigiDocConf_xsdPath(swigCPtr, this);
  }

  public void setLogLevel(int level) {
    digidocJNI.DigiDocConf_setLogLevel(swigCPtr, this, level);
  }

  public void setLogFile(String file) {
    digidocJNI.DigiDocConf_setLogFile(swigCPtr, this, file);
  }

  public void setTSLCert(byte[] cert) {
    digidocJNI.DigiDocConf_setTSLCert(swigCPtr, this, cert);
  }

  public void addTSLCert(byte[] cert) {
    digidocJNI.DigiDocConf_addTSLCert(swigCPtr, this, cert);
  }

  public void setTSLUrl(String url) {
    digidocJNI.DigiDocConf_setTSLUrl(swigCPtr, this, url);
  }

  public void setOCSPUrls(StringMap urls) {
    digidocJNI.DigiDocConf_setOCSPUrls(swigCPtr, this, StringMap.getCPtr(urls), urls);
  }

  public void setOCSPTMProfiles(StringVector _TMProfiles) {
    digidocJNI.DigiDocConf_setOCSPTMProfiles(swigCPtr, this, StringVector.getCPtr(_TMProfiles), _TMProfiles);
  }

  public void setVerifyServiceCert(byte[] cert) {
    digidocJNI.DigiDocConf_setVerifyServiceCert(swigCPtr, this, cert);
  }

  public void setVerifyServiceUri(String url) {
    digidocJNI.DigiDocConf_setVerifyServiceUri(swigCPtr, this, url);
  }

}
