/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ee.ria.libdigidocpp;

public class XmlConfV3 extends ConfV3 {
  private transient long swigCPtr;

  protected XmlConfV3(long cPtr, boolean cMemoryOwn) {
    super(digidocJNI.XmlConfV3_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XmlConfV3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        digidocJNI.delete_XmlConfV3(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public XmlConfV3(String path, String schema) {
    this(digidocJNI.new_XmlConfV3__SWIG_0(path, schema), true);
  }

  public XmlConfV3(String path) {
    this(digidocJNI.new_XmlConfV3__SWIG_1(path), true);
  }

  public XmlConfV3() {
    this(digidocJNI.new_XmlConfV3__SWIG_2(), true);
  }

  public static XmlConfV3 instance() {
    long cPtr = digidocJNI.XmlConfV3_instance();
    return (cPtr == 0) ? null : new XmlConfV3(cPtr, false);
  }

  public int logLevel() {
    return digidocJNI.XmlConfV3_logLevel(swigCPtr, this);
  }

  public String logFile() {
    return digidocJNI.XmlConfV3_logFile(swigCPtr, this);
  }

  public String PKCS11Driver() {
    return digidocJNI.XmlConfV3_PKCS11Driver(swigCPtr, this);
  }

  public String proxyHost() {
    return digidocJNI.XmlConfV3_proxyHost(swigCPtr, this);
  }

  public String proxyPort() {
    return digidocJNI.XmlConfV3_proxyPort(swigCPtr, this);
  }

  public String proxyUser() {
    return digidocJNI.XmlConfV3_proxyUser(swigCPtr, this);
  }

  public String proxyPass() {
    return digidocJNI.XmlConfV3_proxyPass(swigCPtr, this);
  }

  public boolean proxyForceSSL() {
    return digidocJNI.XmlConfV3_proxyForceSSL(swigCPtr, this);
  }

  public boolean proxyTunnelSSL() {
    return digidocJNI.XmlConfV3_proxyTunnelSSL(swigCPtr, this);
  }

  public String digestUri() {
    return digidocJNI.XmlConfV3_digestUri(swigCPtr, this);
  }

  public String signatureDigestUri() {
    return digidocJNI.XmlConfV3_signatureDigestUri(swigCPtr, this);
  }

  public String ocsp(String issuer) {
    return digidocJNI.XmlConfV3_ocsp(swigCPtr, this, issuer);
  }

  public String TSUrl() {
    return digidocJNI.XmlConfV3_TSUrl(swigCPtr, this);
  }

  public String verifyServiceUri() {
    return digidocJNI.XmlConfV3_verifyServiceUri(swigCPtr, this);
  }

  public String PKCS12Cert() {
    return digidocJNI.XmlConfV3_PKCS12Cert(swigCPtr, this);
  }

  public String PKCS12Pass() {
    return digidocJNI.XmlConfV3_PKCS12Pass(swigCPtr, this);
  }

  public boolean PKCS12Disable() {
    return digidocJNI.XmlConfV3_PKCS12Disable(swigCPtr, this);
  }

  public boolean TSLAutoUpdate() {
    return digidocJNI.XmlConfV3_TSLAutoUpdate(swigCPtr, this);
  }

  public String TSLCache() {
    return digidocJNI.XmlConfV3_TSLCache(swigCPtr, this);
  }

  public boolean TSLOnlineDigest() {
    return digidocJNI.XmlConfV3_TSLOnlineDigest(swigCPtr, this);
  }

  public int TSLTimeOut() {
    return digidocJNI.XmlConfV3_TSLTimeOut(swigCPtr, this);
  }

  public void setProxyHost(String host) {
    digidocJNI.XmlConfV3_setProxyHost(swigCPtr, this, host);
  }

  public void setProxyPort(String port) {
    digidocJNI.XmlConfV3_setProxyPort(swigCPtr, this, port);
  }

  public void setProxyUser(String user) {
    digidocJNI.XmlConfV3_setProxyUser(swigCPtr, this, user);
  }

  public void setProxyPass(String pass) {
    digidocJNI.XmlConfV3_setProxyPass(swigCPtr, this, pass);
  }

  public void setProxyTunnelSSL(boolean enable) {
    digidocJNI.XmlConfV3_setProxyTunnelSSL(swigCPtr, this, enable);
  }

  public void setPKCS12Cert(String cert) {
    digidocJNI.XmlConfV3_setPKCS12Cert(swigCPtr, this, cert);
  }

  public void setPKCS12Pass(String pass) {
    digidocJNI.XmlConfV3_setPKCS12Pass(swigCPtr, this, pass);
  }

  public void setPKCS12Disable(boolean disable) {
    digidocJNI.XmlConfV3_setPKCS12Disable(swigCPtr, this, disable);
  }

  public void setTSLOnlineDigest(boolean enable) {
    digidocJNI.XmlConfV3_setTSLOnlineDigest(swigCPtr, this, enable);
  }

  public void setTSLTimeOut(int timeOut) {
    digidocJNI.XmlConfV3_setTSLTimeOut(swigCPtr, this, timeOut);
  }

  public void setTSUrl(String url) {
    digidocJNI.XmlConfV3_setTSUrl(swigCPtr, this, url);
  }

}
