/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ee.ria.libdigidocpp;

public class DataFiles {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DataFiles(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataFiles obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        digidocJNI.delete_DataFiles(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DataFiles() {
    this(digidocJNI.new_DataFiles__SWIG_0(), true);
  }

  public DataFiles(long n) {
    this(digidocJNI.new_DataFiles__SWIG_1(n), true);
  }

  public long size() {
    return digidocJNI.DataFiles_size(swigCPtr, this);
  }

  public long capacity() {
    return digidocJNI.DataFiles_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    digidocJNI.DataFiles_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return digidocJNI.DataFiles_isEmpty(swigCPtr, this);
  }

  public void clear() {
    digidocJNI.DataFiles_clear(swigCPtr, this);
  }

  public void add(DataFile x) {
    digidocJNI.DataFiles_add(swigCPtr, this, DataFile.getCPtr(x), x);
  }

  public DataFile get(int i) {
    long cPtr = digidocJNI.DataFiles_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new DataFile(cPtr, false);
  }

  public void set(int i, DataFile val) {
    digidocJNI.DataFiles_set(swigCPtr, this, i, DataFile.getCPtr(val), val);
  }

}
