/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ee.ria.libdigidocpp;

public class Signatures {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Signatures(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Signatures obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        digidocJNI.delete_Signatures(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Signatures() {
    this(digidocJNI.new_Signatures__SWIG_0(), true);
  }

  public Signatures(long n) {
    this(digidocJNI.new_Signatures__SWIG_1(n), true);
  }

  public long size() {
    return digidocJNI.Signatures_size(swigCPtr, this);
  }

  public long capacity() {
    return digidocJNI.Signatures_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    digidocJNI.Signatures_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return digidocJNI.Signatures_isEmpty(swigCPtr, this);
  }

  public void clear() {
    digidocJNI.Signatures_clear(swigCPtr, this);
  }

  public void add(Signature x) {
    digidocJNI.Signatures_add(swigCPtr, this, Signature.getCPtr(x), x);
  }

  public Signature get(int i) {
    long cPtr = digidocJNI.Signatures_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Signature(cPtr, false);
  }

  public void set(int i, Signature val) {
    digidocJNI.Signatures_set(swigCPtr, this, i, Signature.getCPtr(val), val);
  }

}
