/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ee.ria.libdigidocpp;

public class Signer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Signer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Signer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        digidocJNI.delete_Signer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public byte[] sign(String method, byte[] digest) {
    return digidocJNI.Signer_sign(swigCPtr, this, method, digest);
  }

  public String method() {
    return digidocJNI.Signer_method(swigCPtr, this);
  }

  public String profile() {
    return digidocJNI.Signer_profile(swigCPtr, this);
  }

  public boolean usingENProfile() {
    return digidocJNI.Signer_usingENProfile(swigCPtr, this);
  }

  public String city() {
    return digidocJNI.Signer_city(swigCPtr, this);
  }

  public String streetAddress() {
    return digidocJNI.Signer_streetAddress(swigCPtr, this);
  }

  public String stateOrProvince() {
    return digidocJNI.Signer_stateOrProvince(swigCPtr, this);
  }

  public String postalCode() {
    return digidocJNI.Signer_postalCode(swigCPtr, this);
  }

  public String countryName() {
    return digidocJNI.Signer_countryName(swigCPtr, this);
  }

  public StringVector signerRoles() {
    return new StringVector(digidocJNI.Signer_signerRoles(swigCPtr, this), true);
  }

  public void setMethod(String method) {
    digidocJNI.Signer_setMethod(swigCPtr, this, method);
  }

  public void setProfile(String profile) {
    digidocJNI.Signer_setProfile(swigCPtr, this, profile);
  }

  public void setENProfile(boolean enable) {
    digidocJNI.Signer_setENProfile(swigCPtr, this, enable);
  }

  public void setSignatureProductionPlace(String city, String stateOrProvince, String postalCode, String countryName) {
    digidocJNI.Signer_setSignatureProductionPlace(swigCPtr, this, city, stateOrProvince, postalCode, countryName);
  }

  public void setSignatureProductionPlaceV2(String city, String streetAddress, String stateOrProvince, String postalCode, String countryName) {
    digidocJNI.Signer_setSignatureProductionPlaceV2(swigCPtr, this, city, streetAddress, stateOrProvince, postalCode, countryName);
  }

  public void setSignerRoles(StringVector signerRoles) {
    digidocJNI.Signer_setSignerRoles(swigCPtr, this, StringVector.getCPtr(signerRoles), signerRoles);
  }

}
