/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace digidoc {

using System;
using System.Runtime.InteropServices;

public class ADoc : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ADoc(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ADoc obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ADoc() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          digidocPINVOKE.delete_ADoc(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public virtual void save() {
    digidocPINVOKE.ADoc_save(swigCPtr);
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void saveTo(string path) {
    digidocPINVOKE.ADoc_saveTo(swigCPtr, path);
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void addDocument(Document document) {
    digidocPINVOKE.ADoc_addDocument(swigCPtr, Document.getCPtr(document));
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual Document getDocument(uint id) {
    Document ret = new Document(digidocPINVOKE.ADoc_getDocument(swigCPtr, id), true);
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void removeDocument(uint id) {
    digidocPINVOKE.ADoc_removeDocument(swigCPtr, id);
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual uint documentCount() {
    uint ret = digidocPINVOKE.ADoc_documentCount(swigCPtr);
    return ret;
  }

  public virtual ADoc.DocumentType documentType() {
    ADoc.DocumentType ret = (ADoc.DocumentType)digidocPINVOKE.ADoc_documentType(swigCPtr);
    return ret;
  }

  public virtual void addSignature(byte[] signature) {
    digidocPINVOKE.ADoc_addSignature(swigCPtr, digidocPINVOKE.ByteVector_to(signature, signature.Length));
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual Signature getSignature(uint id) {
    IntPtr cPtr = digidocPINVOKE.ADoc_getSignature(swigCPtr, id);
    Signature ret = (cPtr == IntPtr.Zero) ? null : new Signature(cPtr, false);
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void removeSignature(uint id) {
    digidocPINVOKE.ADoc_removeSignature(swigCPtr, id);
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual uint signatureCount() {
    uint ret = digidocPINVOKE.ADoc_signatureCount(swigCPtr);
    return ret;
  }

  public enum DocumentType {
    UnknownType = 0,
    BDocType = 1,
    DDocType = 2
  }

}

}
