/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace digidoc {

using System;
using System.Runtime.InteropServices;

public class BDoc : ADoc {
  private HandleRef swigCPtr;

  internal BDoc(IntPtr cPtr, bool cMemoryOwn) : base(digidocPINVOKE.BDoc_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(BDoc obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~BDoc() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          digidocPINVOKE.delete_BDoc(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public BDoc() : this(digidocPINVOKE.new_BDoc__SWIG_0(), true) {
  }

  public BDoc(string path) : this(digidocPINVOKE.new_BDoc__SWIG_1(path), true) {
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void save() {
    digidocPINVOKE.BDoc_save(swigCPtr);
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void saveTo(string path) {
    digidocPINVOKE.BDoc_saveTo(swigCPtr, path);
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void addDocument(Document document) {
    digidocPINVOKE.BDoc_addDocument(swigCPtr, Document.getCPtr(document));
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
  }

  public override Document getDocument(uint id) {
    Document ret = new Document(digidocPINVOKE.BDoc_getDocument(swigCPtr, id), true);
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void removeDocument(uint id) {
    digidocPINVOKE.BDoc_removeDocument(swigCPtr, id);
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
  }

  public override uint documentCount() {
    uint ret = digidocPINVOKE.BDoc_documentCount(swigCPtr);
    return ret;
  }

  public override ADoc.DocumentType documentType() {
    ADoc.DocumentType ret = (ADoc.DocumentType)digidocPINVOKE.BDoc_documentType(swigCPtr);
    return ret;
  }

  public uint newSignatureId() {
    uint ret = digidocPINVOKE.BDoc_newSignatureId(swigCPtr);
    return ret;
  }

  public override Signature getSignature(uint id) {
    IntPtr cPtr = digidocPINVOKE.BDoc_getSignature(swigCPtr, id);
    Signature ret = (cPtr == IntPtr.Zero) ? null : new Signature(cPtr, false);
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void removeSignature(uint id) {
    digidocPINVOKE.BDoc_removeSignature(swigCPtr, id);
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
  }

  public override uint signatureCount() {
    uint ret = digidocPINVOKE.BDoc_signatureCount(swigCPtr);
    return ret;
  }

  public enum Type {
    BES,
    TM
  }

}

}
