/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace digidoc {

using System;
using System.Runtime.InteropServices;

public class DDoc : ADoc {
  private HandleRef swigCPtr;

  internal DDoc(IntPtr cPtr, bool cMemoryOwn) : base(digidocPINVOKE.DDoc_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(DDoc obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~DDoc() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          digidocPINVOKE.delete_DDoc(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public DDoc() : this(digidocPINVOKE.new_DDoc__SWIG_0(), true) {
  }

  public DDoc(string path) : this(digidocPINVOKE.new_DDoc__SWIG_1(path), true) {
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void save() {
    digidocPINVOKE.DDoc_save(swigCPtr);
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void saveTo(string path) {
    digidocPINVOKE.DDoc_saveTo(swigCPtr, path);
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void addDocument(Document document) {
    digidocPINVOKE.DDoc_addDocument(swigCPtr, Document.getCPtr(document));
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
  }

  public override Document getDocument(uint id) {
    Document ret = new Document(digidocPINVOKE.DDoc_getDocument(swigCPtr, id), true);
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void removeDocument(uint id) {
    digidocPINVOKE.DDoc_removeDocument(swigCPtr, id);
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
  }

  public override uint documentCount() {
    uint ret = digidocPINVOKE.DDoc_documentCount(swigCPtr);
    return ret;
  }

  public override ADoc.DocumentType documentType() {
    ADoc.DocumentType ret = (ADoc.DocumentType)digidocPINVOKE.DDoc_documentType(swigCPtr);
    return ret;
  }

  public override void addSignature(byte[] signature) {
    digidocPINVOKE.DDoc_addSignature(swigCPtr, digidocPINVOKE.ByteVector_to(signature, signature.Length));
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
  }

  public override Signature getSignature(uint id) {
    IntPtr cPtr = digidocPINVOKE.DDoc_getSignature(swigCPtr, id);
    Signature ret = (cPtr == IntPtr.Zero) ? null : new Signature(cPtr, false);
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void removeSignature(uint id) {
    digidocPINVOKE.DDoc_removeSignature(swigCPtr, id);
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
  }

  public override uint signatureCount() {
    uint ret = digidocPINVOKE.DDoc_signatureCount(swigCPtr);
    return ret;
  }

}

}
