/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace digidoc {

using System;
using System.Runtime.InteropServices;

public class digidoc {
  public static string appInfo() {
    string ret = digidocPINVOKE.appInfo();
    return ret;
  }

  public static void initialize(string appInfo) {
    digidocPINVOKE.initialize__SWIG_0(appInfo);
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void initialize() {
    digidocPINVOKE.initialize__SWIG_1();
  }

  public static void terminate() {
    digidocPINVOKE.terminate();
  }

  public static string version() {
    string ret = digidocPINVOKE.version();
    return ret;
  }

}

}
