/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ee.ria.libdigidocpp;

public class Signature {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Signature(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Signature obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        digidocJNI.delete_Signature(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static String getPOLv1() {
    return digidocJNI.Signature_POLv1_get();
  }

  public static String getPOLv2() {
    return digidocJNI.Signature_POLv2_get();
  }

  public String id() {
    return digidocJNI.Signature_id(swigCPtr, this);
  }

  public String claimedSigningTime() {
    return digidocJNI.Signature_claimedSigningTime(swigCPtr, this);
  }

  public String trustedSigningTime() {
    return digidocJNI.Signature_trustedSigningTime(swigCPtr, this);
  }

  public String signatureMethod() {
    return digidocJNI.Signature_signatureMethod(swigCPtr, this);
  }

  public void validate() {
    digidocJNI.Signature_validate__SWIG_0(swigCPtr, this);
  }

  public byte[] dataToSign() {
    return digidocJNI.Signature_dataToSign(swigCPtr, this);
  }

  public void setSignatureValue(byte[] signatureValue) {
    digidocJNI.Signature_setSignatureValue(swigCPtr, this, signatureValue);
  }

  public void extendSignatureProfile(String profile) {
    digidocJNI.Signature_extendSignatureProfile(swigCPtr, this, profile);
  }

  public String policy() {
    return digidocJNI.Signature_policy(swigCPtr, this);
  }

  public String SPUri() {
    return digidocJNI.Signature_SPUri(swigCPtr, this);
  }

  public String profile() {
    return digidocJNI.Signature_profile(swigCPtr, this);
  }

  public String city() {
    return digidocJNI.Signature_city(swigCPtr, this);
  }

  public String stateOrProvince() {
    return digidocJNI.Signature_stateOrProvince(swigCPtr, this);
  }

  public String postalCode() {
    return digidocJNI.Signature_postalCode(swigCPtr, this);
  }

  public String countryName() {
    return digidocJNI.Signature_countryName(swigCPtr, this);
  }

  public StringVector signerRoles() {
    return new StringVector(digidocJNI.Signature_signerRoles(swigCPtr, this), true);
  }

  public String OCSPProducedAt() {
    return digidocJNI.Signature_OCSPProducedAt(swigCPtr, this);
  }

  public byte[] OCSPNonce() {
    return digidocJNI.Signature_OCSPNonce(swigCPtr, this);
  }

  public String TimeStampTime() {
    return digidocJNI.Signature_TimeStampTime(swigCPtr, this);
  }

  public String ArchiveTimeStampTime() {
    return digidocJNI.Signature_ArchiveTimeStampTime(swigCPtr, this);
  }

  public String streetAddress() {
    return digidocJNI.Signature_streetAddress(swigCPtr, this);
  }

  public String signedBy() {
    return digidocJNI.Signature_signedBy(swigCPtr, this);
  }

  public void validate(String policy) {
    digidocJNI.Signature_validate__SWIG_1(swigCPtr, this, policy);
  }

  public byte[] signingCertificateDer() {
    return digidocJNI.Signature_signingCertificateDer(swigCPtr, this);
  }

  public byte[] OCSPCertificateDer() {
    return digidocJNI.Signature_OCSPCertificateDer(swigCPtr, this);
  }

  public byte[] TimeStampCertificateDer() {
    return digidocJNI.Signature_TimeStampCertificateDer(swigCPtr, this);
  }

  public byte[] ArchiveTimeStampCertificateDer() {
    return digidocJNI.Signature_ArchiveTimeStampCertificateDer(swigCPtr, this);
  }

}
