/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ee.ria.libdigidocpp;

public class Signatures extends java.util.AbstractList<Signature> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Signatures(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Signatures obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        digidocJNI.delete_Signatures(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Signatures(Signature[] initialElements) {
    this();
    for (Signature element : initialElements) {
      add(element);
    }
  }

  public Signatures(Iterable<Signature> initialElements) {
    this();
    for (Signature element : initialElements) {
      add(element);
    }
  }

  public Signature get(int index) {
    return doGet(index);
  }

  public Signature set(int index, Signature e) {
    return doSet(index, e);
  }

  public boolean add(Signature e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Signature e) {
    modCount++;
    doAdd(index, e);
  }

  public Signature remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public Signatures() {
    this(digidocJNI.new_Signatures__SWIG_0(), true);
  }

  public Signatures(Signatures other) {
    this(digidocJNI.new_Signatures__SWIG_1(Signatures.getCPtr(other), other), true);
  }

  public long capacity() {
    return digidocJNI.Signatures_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    digidocJNI.Signatures_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return digidocJNI.Signatures_isEmpty(swigCPtr, this);
  }

  public void clear() {
    digidocJNI.Signatures_clear(swigCPtr, this);
  }

  public Signatures(int count, Signature value) {
    this(digidocJNI.new_Signatures__SWIG_2(count, Signature.getCPtr(value), value), true);
  }

  private int doSize() {
    return digidocJNI.Signatures_doSize(swigCPtr, this);
  }

  private void doAdd(Signature x) {
    digidocJNI.Signatures_doAdd__SWIG_0(swigCPtr, this, Signature.getCPtr(x), x);
  }

  private void doAdd(int index, Signature x) {
    digidocJNI.Signatures_doAdd__SWIG_1(swigCPtr, this, index, Signature.getCPtr(x), x);
  }

  private Signature doRemove(int index) {
    long cPtr = digidocJNI.Signatures_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Signature(cPtr, false);
  }

  private Signature doGet(int index) {
    long cPtr = digidocJNI.Signatures_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Signature(cPtr, false);
  }

  private Signature doSet(int index, Signature val) {
    long cPtr = digidocJNI.Signatures_doSet(swigCPtr, this, index, Signature.getCPtr(val), val);
    return (cPtr == 0) ? null : new Signature(cPtr, false);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    digidocJNI.Signatures_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
